/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;


import java.math.BigDecimal;


// This is for file handling and IO exceptions.
import java.io.IOException;
import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.*;


// This is for HTTP requests
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;



// Import Java Timer
import java.util.Timer;
import java.util.TimerTask;

//Import Executors for scheduling tasks
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.Date;

// Import Java Scanner 
import java.util.Scanner;

// JSON parsing for prices 
import org.json.JSONObject;

// Import Stock Visualizer
import org.example.StockVisualizer;
import javafx.stage.Stage;
import javafx.application.Application;
import javafx.scene.chart.XYChart;





public class App {
    public String getGreeting() {
        // the app is alive
        return "hello world!";
    }



    public static void main(String[] args) throws IOException, InterruptedException {

        // this is my scanner for user input
        Scanner scanner = new Scanner(System.in);
        System.out.print("Enter stock symbol: ");
        String symbol = scanner.nextLine();
        scanner.close();

        // then I am running the ui application on java fx
        Application.launch(StockVisualizer.class, new String[] { symbol });
        
 
    }


}
