/*
 * this source file was generated by the Gradle 'init' task
 */
package org.example;

// java Import for Big Decimal
import java.math.BigDecimal;


// this is for file handling and IO exceptions.
import java.io.IOException;
import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.*;


// this is for HTTP requests
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;



// json parsing for prices 
import org.json.JSONObject;







public class FinHub {
    public String apiGreeting() {
        return "this is the finhub api class";
    }

    public static String fetchStockInfo(String tickerName) throws IOException, InterruptedException {
        /* 
        
        this function utilizes the fihub api to get stock info. 
        put your api keys in the gradle.properties file as FINNHUB_API_KEY=insertyourkey

        */
        try {

            
            String apiKey = System.getenv("FINNHUB_API_KEY");

            // fetch format
            String url = String.format(
                "https://finnhub.io/api/v1/quote?symbol=%s&token=%s",
                tickerName,
                apiKey
            );

            HttpClient client = HttpClient.newHttpClient();
            HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create(url))
                .GET()
                .build();

        
            HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());

            // json parser
            JSONObject obj = new JSONObject(response.body());
            BigDecimal cValue = BigDecimal.valueOf(obj.getDouble("c"));

            // transfer to string and return from Big Decimal
            return cValue.toString();
            
    
        } catch (IOException e) {
            System.out.println("error fetching stock data: " + e.getMessage());
            throw e;
        }
    }
}
